### ISSUE TITLE
Unable to download instructions

### ISSUE THREAD

**Issue by Qiangong2** [luke-eisenbraun/LegoDownloader#1]
I'm trying to download instructions on Windows with PS, but I keep getting this:  https://paste.ubuntu.com/p/jPXnyh3nbN/

**Comment by luke-eisenbraun** [comment]
It looks like Lego changed their API. Ill look at getting a fix but can't promise anything. The brickset link still works and contains most of the links. You can just run wget on the whole list. Only downside is they won't be organized by themes or have the nice setnames like I have here.

**Comment by Qiangong2** [comment]
> It looks like Lego changed their API. Ill look at getting a fix but can't promise anything. The brickset link still works and contains most of the links. You can just run wget on the whole list. Only downside is they won't be organized by themes or have the nice setnames like I have here.

Yeah, I have done that, but it just lists the set numbers. Not exactly the easiest to sort

**Comment by luke-eisenbraun** [comment]
Script has been updated and should now pull down all the instructions
