### ISSUE TITLE
json file doesn't save previous sets

### ISSUE THREAD

**Issue by Qiangong2** [luke-eisenbraun/LegoDownloader#6]
the saved_sets json file that is supposed to be created, doesn't save any sets to it. This means it has to redownload every single set each time you run the script. Ideally, it would skip over all of the sets that have been downloaded

**Comment by luke-eisenbraun** [comment]
The sets aren't saved until the end (thus requiring a full run on first run to set and save it). That said, the script checks if the filepath exists before downloading again (line 130) so if a set was previously downloaded it won't do it again.
